- .npmrc
- apps/api/package.json
- apps/api/src/modules/auth/auth.service.ts
- apps/web/package.json
- apps/web/src/common/components/Layout/index.tsx
- apps/web/src/common/components/Layout/styled.ts
- apps/web/src/common/context/UserContext/hooks/useUserData/index.ts
- apps/web/src/common/context/UserContext/index.test.tsx
- apps/web/src/common/context/UserContext/index.tsx
- apps/web/src/common/context/UserContext/types.ts
- apps/web/src/common/hoc/withGuard/index.test.tsx
- apps/web/src/common/hoc/withGuard/index.tsx
- apps/web/src/common/types/prisma.ts
- apps/web/src/pages/_app.tsx
- pnpm-lock.yaml
- Implement Layout Component (with stupid header and footer)
- Implement UserContext for storing user data (with loader)
anyone who wants to use user data can call `useUser()` to get user's `firstname`, `type`, `isVerified`
- Implement page guard HOC
anyone who wants to guard their page can use `withGuard()` when exporting the component
- the first argument is the Component you want to export
- the second argument is array of the allowed user type 
```tsx
export default Example
// allow only Actor
export default withGuard(Example, [ UserType.ACTOR ])
// allow only Admin and Casting
export default withGuard(Example, [ UserType.ADMIN, UserType.CASTING ])
```
> [60] Implement page guard

- apps/web/next.config.js
- apps/web/src/modules/job/components/Card/components/Footer/index.tsx
- apps/web/src/modules/job/components/Card/components/Header/index.tsx
- apps/web/src/modules/job/components/Card/components/ShootingDetail/index.tsx
- Optimize import module from `@mui/icons-material`
-
> [6] Optimize module import

- apps/api/src/modules/job/job.controller.ts
- apps/api/src/modules/job/job.repository.ts
- apps/api/src/modules/job/job.service.spec.ts
- apps/api/src/modules/job/job.service.ts
- packages/database/package.json
- packages/dtos/src/job.ts
- Implement `GET job/:id` with unit test
- This endpoint doesn't prevent unverified user yet (@palmcm will implement a new guard for that)
> [14] Implement job detail API

- apps/api/src/modules/auth/auth.controller.ts
- apps/api/src/modules/auth/auth.repository.ts
- apps/api/src/modules/auth/auth.service.spec.ts
- apps/api/src/modules/auth/auth.service.ts
- Write test for verify password service
- add createJwt to signup service
-
> [41] Write unit test for log in API

- .dockerignore
- .github/workflows/publish-docker-backend.yml
- .github/workflows/publish-docker-frontend.yml
- apps/api/Dockerfile
- apps/web/.env.beta
- apps/web/.env.dev
- apps/web/.env.prod
- apps/web/Dockerfile
- apps/web/next.config.js
- apps/web/package.json
- package.json
- packages/database/package.json
- packages/dtos/index.ts
- packages/dtos/package.json
- packages/swagger-utils/index.ts
- packages/swagger-utils/package.json
- packages/swagger-utils/tsconfig.json
- pnpm-lock.yaml
- Implement Dockerfile for building the image for both frontend and backend
- Fix DTOS build error when use value from prisma (Such as Gender)
- Implement github actions to deploy the image to docker registry when push to `beta`, `dev`, `main`
- I will try to manual trigger on this branch to show that it's working
> [4] Setup github actions and fix dtos module

- apps/api/src/modules/job/job.service.spec.ts
- fix missing ```isVerified``` for mock user in job unit test //sorry for error merged :P
- ```cd apps/api```
- ```pnpm test```
> test: add isVerified in job test

- apps/web/jest.config.js
- apps/web/package.json
- pnpm-lock.yaml
- Optimize module loader when coverage test especially for `@mui/icons-material`
Before:
After:
> [6] Optimize module loader when test coverage

- apps/api/src/modules/job/job.controller.ts
- apps/api/src/modules/job/job.repository.ts
- apps/api/src/modules/job/job.service.spec.ts
- apps/api/src/modules/job/job.service.ts
- packages/dtos/src/job.ts
- Implement search job in ```GET /job``` for every param
- refactor unit test for the others ```find job``` related, I have no idea how to write unit test for search job filtered
- https://api-dev.modela.miello.dev/swagger
- login at ```POST /auth/login``` with email: ```ayame@hololive.com```, password: ```ayame123```
- try to query at ```GET /job``` with every combination possible, for example
- startDate-endDate: ```2023-02-01T00:00:00Z``` to ```2023-02-10T00:00:00Z```
- startTime-endTime: ```1970-01-01T00:00:00Z``` to ```1970-01-01T23:59:59Z```
- location: ```Suite 548``` , ```Apt. 335``` , ```Apt. 403```
- age: ```10``` to ```30```
- minWage-maxWage: ```0``` to ```1000000```
- status: ```OPEN```, ```CLOSE```, OPEN and CLOSE //shift-click to select more than one in swagger
- gender: …
> [24] Implement get filtered posted job API @GET

- apps/web/src/modules/signup/actor/constants.ts
- Fix ssn field that missing from signup actor form
- https://dev.modela.miello.dev/signup/actor
> [45] Fix missing ssn field from actor form

- apps/web/src/common/components/Navbar/components/NavbarMobile/index.tsx
- apps/web/src/common/components/Navbar/components/NavbarProfile/index.tsx
- apps/web/src/common/components/Navbar/hooks/useNavMenu/index.tsx
- apps/web/src/common/context/UserContext/hooks/useUserData/index.test.tsx
- apps/web/src/common/context/UserContext/hooks/useUserData/index.ts
- apps/web/src/common/context/UserContext/index.tsx
- apps/web/src/common/context/UserContext/types.ts
- apps/web/src/common/hoc/withGuard/index.test.tsx
- apps/web/src/common/hoc/withGuard/index.tsx
- apps/web/src/common/hoc/withNotLoggedInGuard/index.test.tsx
- apps/web/src/common/hoc/withNotLoggedInGuard/index.tsx
- apps/web/src/common/utils/testing/mockUser/index.test.tsx
- apps/web/src/common/utils/testing/mockUser/index.ts
- apps/web/src/modules/job/components/JobCardFooter/index.tsx
- apps/web/src/modules/job/components/JobCardHeader/index.tsx
- apps/web/src/modules/signup/actor/index.tsx
- apps/web/src/modules/signup/casting/index.tsx
- Add refetch and reset to `useUser`
- Add `withNotLoggedInGuard`
- Fix missing field in navbar when not verified
> [60] Add refetch and reset to useUser

- apps/api/src/modules/job/job.controller.ts
- apps/api/src/modules/job/job.repository.ts
- apps/api/src/modules/job/job.service.spec.ts
- apps/api/src/modules/job/job.service.ts
- packages/dtos/src/job.ts
- Implemented post jobs API
- Currently the job status will default to OPEN.
- Also includes a simple test unit.
- Swagger -> Post /job
> [28] Implement post a jobs API @POST

- apps/web/src/modules/job/components/JobCardHeader/index.test.tsx
- apps/web/src/modules/job/components/JobCardHeader/index.tsx
- apps/web/src/modules/job/components/JobCardHeader/styled.ts
- apps/web/src/modules/job/components/JobCardHeader/types.ts
- apps/web/src/modules/job/detail/components/JobCard/index.test.tsx
- apps/web/src/modules/job/detail/components/JobCard/index.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/components/JobCard/index.tsx
- Fix style in JobCard
- Redirect to report and edit page when click on icon
- Hide edit icon when JobStatus is not open
- Not merge to dev yet
> [13] fix jobcard

- apps/web/src/modules/job/list/pages/hooks/useJobListData/index.ts
- apps/web/src/modules/job/list/pages/index.tsx
- ![image](https://user-images.githubusercontent.com/73303542/218402483-d6a77c0a-f00a-47a8-ac42-157971af0a3c.png)
- Add createPost Button
> [18] Implement casting's posted jobs page

- apps/web/src/common/components/Navbar/components/NavbarDesktop/index.tsx
- apps/web/src/common/components/Navbar/components/NavbarDesktop/styled.ts
- apps/web/src/common/components/Navbar/hooks/useNavMenu/index.tsx
- apps/web/src/common/context/UserContext/types.ts
- apps/web/src/modules/job/detail/pages/index.test.tsx
- apps/web/src/modules/job/detail/pages/index.tsx
- apps/web/src/modules/job/list/pages/hooks/useJobListData/index.ts
- apps/web/src/modules/job/list/pages/index.test.tsx
- apps/web/src/modules/job/list/pages/index.tsx
- apps/web/src/modules/login/constants.ts
- apps/web/src/modules/login/hooks/useLoginForm/index.tsx
- apps/web/src/modules/login/hooks/useLoginForm/schema.ts
- apps/web/src/modules/login/index.tsx
- apps/web/src/modules/login/styled.ts
- apps/web/src/pages/login.tsx
- Implement Signin page
- Implement Logout functionality
- Fix missing page guard
https://dev.modela.miello.dev/login
> [42][37] Implement signin page and logout button functionality

- apps/api/src/modules/job/job.repository.ts
- apps/web/src/common/components/FormController/index.tsx
- apps/web/src/common/components/Navbar/components/NavbarDesktop/index.tsx
- apps/web/src/common/components/Navbar/components/NavbarMobile/index.test.tsx
- apps/web/src/common/components/Navbar/components/NavbarMobile/index.tsx
- apps/web/src/common/components/Navbar/hooks/useNavMenu/index.tsx
- apps/web/src/common/hoc/withGuard/index.test.tsx
- apps/web/src/common/hoc/withNotLoggedInGuard/index.test.tsx
- apps/web/src/common/hoc/withWaitingGuard/index.test.tsx
- apps/web/src/common/utils/testing/mockRouter/index.ts
- apps/web/src/common/utils/testing/mockUser/index.ts
- apps/web/src/modules/job/components/JobCardFooter/index.test.tsx
- apps/web/src/modules/job/components/JobCardHeader/index.test.tsx
- apps/web/src/modules/job/components/JobForm/hooks/useJobForm/index.ts
- apps/web/src/modules/job/components/JobForm/hooks/useJobForm/schema.ts
- apps/web/src/modules/job/components/JobForm/utils/jobAdapter.ts
- apps/web/src/modules/job/detail/components/JobCard/index.test.tsx
- apps/web/src/modules/job/detail/pages/index.test.tsx
- apps/web/src/modules/job/edit/pages/hooks/useInitialValues/index.test.tsx
- apps/web/src/modules/job/edit/pages/index.test.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/components/JobCard/index.test.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/index.test.tsx
- apps/web/src/modules/job/list/pages/index.test.tsx
- apps/web/src/modules/signup/choose/index.test.tsx
- apps/web/src/modules/waiting/index.test.tsx
- Connect edit job page to api
- Add missing job validation
- Fix edit job API
- Implement mock router (will write in notion)
- Add error text to date and time picker
- login at https://dev.modela.miello.dev/login
username: `casting@gmail.com`
password: `password`
- go to https://dev.modela.miello.dev/job/13/edit and try to edit job
> [32][35] Connect edit job page to API

- apps/web/src/modules/job/components/JobForm/hooks/useJobForm/index.ts
- apps/web/src/modules/job/components/JobForm/hooks/useJobForm/schema.ts
- apps/web/src/pages/job/post.tsx
- Connect post job page to API
- https://dev.modela.miello.dev/job/post
> [27]connect to post job API

- apps/api/src/modules/job/job.controller.ts
- apps/api/src/modules/job/job.service.spec.ts
- apps/api/src/modules/job/job.service.ts
- apps/api/src/modules/report/report.controller.ts
- apps/api/src/modules/report/report.service.spec.ts
- apps/api/src/modules/report/report.service.ts
- apps/web/src/modules/report/hooks/useReport/index.ts
- packages/dtos/src/job.ts
- packages/dtos/src/report.ts
- add format for shootingDto
- change DTO to Dto
- remove somecheck in verifyJob
- correct maxWage default in job filter
-
> [EX] Refactor backend

- apps/web/src/modules/job/components/JobCardFooter/index.tsx
- apps/web/src/modules/job/components/JobCardFooter/styled.ts
- apps/web/src/modules/job/components/JobCardHeader/index.tsx
- apps/web/src/modules/job/components/JobCardHeader/styled.ts
- apps/web/src/modules/job/components/JobCardHeader/types.ts
- apps/web/src/modules/job/detail/components/JobCard/components/ShootingDetail/index.tsx
- apps/web/src/modules/job/detail/components/JobCard/index.tsx
- apps/web/src/modules/job/detail/components/JobCard/styled.ts
- apps/web/src/modules/job/list/components/FilterMobileContainer/index.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/components/JobCard/index.tsx
- apps/web/src/modules/job/list/pages/index.tsx
- apps/web/src/modules/login/index.tsx
- apps/web/src/modules/signup/actor/hooks/useActorForm/index.ts
- apps/web/src/modules/signup/casting/hooks/useCastingForm/index.ts
- Fix route from login page to signup page
- Fix overflow text in JobCard
- Fix undefined value when redirect to job or report
- Change onClick in Card to Link
- Remove duplicated date in Card
- Fix responsive apply button
- Signup now refetch data before redirect
- https://dev.modela.miello.dev/login
- (Login First) https://dev.modela.miello.dev/job
> [8][13][18][37] Fix signup route and JobCard issue

- apps/web/src/modules/job/list/components/FilterContainer/index.tsx
- apps/web/src/modules/job/list/components/FilterMobileContainer/index.tsx
- apps/web/src/modules/job/list/pages/hooks/useJobListData/index.ts
- ![image](https://user-images.githubusercontent.com/73303542/218814173-a3f5a4cb-65dd-4f6c-b2af-6db48ee9b21b.png)
- Search background Mobile to grey
- ![image](https://user-images.githubusercontent.com/73303542/218814119-ca07f5e1-ef23-4178-829a-936c39b6305d.png)
- fix divider width in filter
- Change from useEffect check non-negative number to textfield min (Only for filterContainer use in JobListPage)
> [23] fix filter page

- apps/web/src/modules/job/list/pages/hooks/useJobListData/index.ts
- apps/web/src/modules/job/list/pages/types.ts
- ![image](https://user-images.githubusercontent.com/73303542/218923002-10017b99-6911-4c7d-8e49-c78763bb8339.png)
- Fix the API request send with null check for min/max wage
- change initial value for wage from 0 to null
- Because bug only appear on beta so no demo fix appear
> [23] fix no job text

- apps/web/src/common/components/FormController/index.tsx
- apps/web/src/common/components/Navbar/components/NavbarDesktop/index.tsx
- apps/web/src/common/components/Navbar/components/NavbarMenu/index.tsx
- apps/web/src/common/components/Navbar/hooks/useNavMenu/index.tsx
- apps/web/src/modules/job/components/JobForm/constant.ts
- apps/web/src/modules/job/components/JobForm/hooks/useJobForm/schema.ts
- apps/web/src/modules/job/components/JobForm/utils/jobAdapter.ts
- apps/web/src/modules/report/hooks/useReport/schema.ts
- apps/web/src/modules/signup/actor/hooks/useActorForm/schema.ts
- apps/web/src/modules/signup/casting/hooks/useCastingForm/schema.ts
- Fix empty string validation in signup page and post job page
- Fix negative number validation in post job page
- Refactor Navbar to use `<Link />`
Signup Page
- https://dev.modela.miello.dev/signup/actor
- https://dev.modela.miello.dev/signup/casting
Post job page
- (Login first) https://dev.modela.miello.dev/job/post
> [27][32][45][48] Fix empty string and negative number validation

- apps/web/src/common/components/Layout/styled.ts
- apps/web/src/common/components/Navbar/components/NavbarDesktop/index.tsx
- apps/web/src/common/components/Navbar/components/NavbarDesktop/styled.ts
- apps/web/src/common/components/Navbar/components/NavbarMobile/index.tsx
- apps/web/src/common/components/Navbar/components/NavbarMobile/styled.ts
- apps/web/src/common/context/UserContext/index.tsx
- apps/web/src/modules/job/components/JobCardFooter/index.tsx
- apps/web/src/modules/job/components/JobCardHeader/index.tsx
- apps/web/src/modules/job/components/JobCardHeader/styled.ts
- apps/web/src/modules/job/edit/pages/index.tsx
- apps/web/src/modules/job/list/pages/hooks/useJobListData/index.ts
- apps/web/src/modules/job/list/pages/index.tsx
- apps/web/src/modules/report/pages/index.tsx
- apps/web/src/modules/report/pages/styled.ts
- apps/web/src/pages/_document.tsx
- fix navbar icon
- fix job header styling
- fix long job name in report card
- fix report card background
- add shadow to navbar
- fix redirecting after click apply job button
- fix 100vh in ios
> [?] Fix Miscellaneous UI Bug

- apps/web/src/modules/job/list/components/FilterContainer/index.test.tsx
- apps/web/src/modules/job/list/pages/index.test.tsx
- Add unit test for filterContainer and goPostJobButton
-
> [22] [25] unit test for job-list-actor and job-list-filter

- apps/web/src/modules/job/components/JobCardHeader/index.tsx
- apps/web/src/modules/report/pages/styled.ts
- Fix Report and Edit icon button that propagate when click
- Add more width to report container
> [EX] Fix button click propagation and add more report width

- apps/web/src/modules/job/list/pages/index.test.tsx
- fix post job button test failed
> [22] Fix post job button test failed

- apps/api/Dockerfile
- Fix dockerfile that built failed
-
> [EX] Fix backend dockerfile build failed

- .github/workflows/publish-docker-backend.yml
- apps/api/Dockerfile
- apps/web/Dockerfile
- packages/database/package.json
- pnpm-lock.yaml
- Fix build failed due to mock folder removal
-
> [EX] Fix frontend build failed

- apps/api/src/app/app.module.ts
- apps/api/src/modules/job/application/application.controller.ts
- apps/api/src/modules/job/application/application.module.ts
- apps/api/src/modules/job/application/application.repository.ts
- apps/api/src/modules/job/application/application.service.spec.ts
- apps/api/src/modules/job/application/application.service.ts
- apps/api/src/modules/job/job.module.ts
- apps/api/src/modules/job/job.repository.ts
- apps/api/src/modules/job/job.service.spec.ts
- apps/api/src/modules/job/job.service.ts
- apps/api/src/modules/report/report.service.spec.ts
- apps/api/src/modules/report/report.service.ts
- packages/dtos/index.ts
- packages/dtos/src/application.ts
- Implement get all actors that applied for the specific job with jobid API with unit test
- will be edited later if frontend requires more field
- `GET /jobs/{id}/actors` (I recommend you to try this on local, since we don't have any way to apply for job on dev yet)
> [74] Implement get all actors that applied for the specific job with jobid API

- packages/database/prisma/dbml/schema.dbml
- packages/database/prisma/migrations/20230219074209_remove_age_and_add_rejected_reason/migration.sql
- packages/database/prisma/schema.prisma
- packages/database/src/mocks/getBaseMock/index.ts
- remove `age`
- add `rejectedReason`
-
> [EX] Edit database schema (2)

- apps/api/src/modules/user/profile/profile.controller.ts
- apps/api/src/modules/user/profile/profile.module.ts
- apps/api/src/modules/user/profile/profile.repository.ts
- apps/api/src/modules/user/profile/profile.service.spec.ts
- apps/api/src/modules/user/profile/profile.service.ts
- apps/api/src/modules/user/user.module.ts
- packages/dtos/index.ts
- packages/dtos/src/profile.ts
- Implement edit actor profile endpoint
- PUT /profile/actor (recommend to test in local since we can't get profile in dev yet)
> [87] Implement Edit Actor Profile

- apps/api/src/modules/user/profile/profile.controller.ts
- apps/api/src/modules/user/profile/profile.repository.ts
- apps/api/src/modules/user/profile/profile.service.spec.ts
- apps/api/src/modules/user/profile/profile.service.ts
- packages/dtos/src/profile.ts
- packages/frontend-optimizer/index.ts
- implement edit casting profile
- implement get profile for initial data when editing
- please also check edit actor profile since I refactor it
- Login with Casting Account
- https://api-dev.modela.miello.dev/swagger#/profile/ProfileController_getProfile to check what initial data looks like
- https://api-dev.modela.miello.dev/swagger#/profile/ProfileController_editCastingProfile to edit data
- then GET again to check that data is changed
- do this again but for actor
> [90] Implement Edit Casting Profile API

- apps/api/src/modules/auth/misc/jwt-auth.guard.ts
- apps/api/src/modules/auth/misc/jwt.decorator.ts
- apps/api/src/modules/job/application/application.controller.ts
- apps/api/src/modules/job/job.controller.ts
- apps/api/src/modules/report/report.controller.ts
- apps/api/src/modules/user/profile/profile.controller.ts
- apps/api/src/modules/user/user.controller.ts
- make UseAuthGuard block unverified user
- remove UseTypeAuthGuard 
- add UseUnverifyGuard
-
> [EX] remove UseTypeAuthGuard and add UseUnverifyGuard

- packages/dtos/src/report.ts
- added dto for single get job by id and get job by report
- also refactored the base dto class
- none, note that this is completely untested
> [N/A] Added Dto for @GET report variants

- apps/api/src/modules/job/job.service.spec.ts
- apps/web/src/common/components/Chip/index.test.tsx
- apps/web/src/common/components/MenuBar/index.test.tsx
- apps/web/src/common/components/MenuBar/index.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCard/index.test.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCard/index.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCardHeader/index.test.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCardHeader/index.tsx
- apps/web/src/modules/job/appliedActor/components/ActorFilter/constants.ts
- apps/web/src/modules/job/appliedActor/components/ActorFilter/index.test.tsx
- apps/web/src/modules/job/appliedActor/components/ActorFilterModal/index.test.tsx
- apps/web/src/modules/job/appliedActor/pages/hooks/useActorData/index.test.tsx
- apps/web/src/modules/job/appliedActor/pages/index.test.tsx
- apps/web/src/modules/job/components/JobMenu/hooks/useSummaryData/index.test.tsx
- apps/web/src/modules/job/components/JobMenu/index.test.tsx
- apps/web/src/modules/job/components/JobMenu/index.tsx
- packages/dtos/src/application.ts
- add tests for applied actor list page
- fix some actor card bug
> [73] Implement applied actor list page test

- apps/api/src/modules/job/job.controller.ts
- apps/api/src/modules/report/report.controller.ts
- apps/web/src/modules/job/components/JobForm/hooks/useJobForm/index.ts
- apps/web/src/modules/job/components/JobMenu/hooks/useSummaryData/index.test.tsx
- apps/web/src/modules/job/components/JobMenu/hooks/useSummaryData/index.ts
- apps/web/src/modules/job/detail/pages/hooks/useJobData/index.ts
- apps/web/src/modules/job/detail/pages/index.test.tsx
- apps/web/src/modules/job/detail/pages/index.tsx
- apps/web/src/modules/job/edit/pages/hooks/useInitialValues/index.test.tsx
- apps/web/src/modules/job/edit/pages/hooks/useInitialValues/index.ts
- apps/web/src/modules/job/list/pages/hooks/useJobListData/index.ts
- apps/web/src/modules/report/hooks/useReport/index.ts
- rename `/job` to `/jobs`
- rename `/report` to `/reports`
- fix job detail page bug (for actor)
-
> [EX] Rename API endpoint

- apps/api/src/modules/resume/resume.controller.ts
- apps/api/src/modules/resume/resume.respository.ts
- apps/api/src/modules/resume/resume.service.spec.ts
- apps/api/src/modules/resume/resume.service.ts
- added API for GETting resumes (both all from user variant and specific ID variant)
- login and check swagger
> [117] Implement actor view resumes API @GET

- apps/api/src/modules/auth/info/info.controller.ts
- apps/api/src/modules/auth/info/info.repository.ts
- apps/api/src/modules/auth/info/info.service.ts
- apps/api/src/modules/auth/misc/jwt.service.ts
- packages/dtos/src/info.ts
- fix that when update need to set user status to pending
- add endpoint GET PUT for casting info
-
> [111] Implement API for for editing rejected casting data @PUT

- apps/web/src/common/components/MenuBar/index.test.tsx
- apps/web/src/common/components/MenuBar/index.tsx
- apps/web/src/common/components/MenuBar/styled.ts
- apps/web/src/common/components/Navbar/components/NavbarDesktop/styled.ts
- apps/web/src/common/components/Navbar/components/NavbarMobile/styled.ts
- apps/web/src/modules/job/appliedActor/pages/index.test.tsx
- apps/web/src/modules/job/appliedActor/pages/index.tsx
- apps/web/src/modules/job/appliedActor/pages/styled.ts
- apps/web/src/modules/job/components/JobMenu/index.test.tsx
- apps/web/src/modules/job/components/JobMenu/index.tsx
- apps/web/src/modules/job/components/JobMenu/styled.ts
- apps/web/src/modules/job/detail/pages/styled.ts
- Make menu bar responsive
- login with `casting4@gmail.com` and go to https://dev.modela.miello.dev/job/10/actor
- don't forget to check this page on actor side too (to ensure that I didn't mess something up)
> [73] Make Menu Bar responsive

- apps/api/src/modules/report/report.controller.ts
- apps/api/src/modules/report/report.repository.ts
- apps/api/src/modules/report/report.service.spec.ts
- apps/api/src/modules/report/report.service.ts
- implemented API for getting report for a job ID
- implemented cancelling a job with an ID
- implemented clearing all reports for a job with an ID
- check swagger
> [123][126][129] Implement get report and cancel job/report API @GET/@PUT

- packages/database/prisma/dbml/schema.dbml
- packages/database/prisma/migrations/20230225175537_make_application_actorid_jobid_unique/migration.sql
- packages/database/prisma/schema.prisma
- packages/database/src/mocks/getBaseMock/index.ts
- make ActorId and JobId unique
- write new mock for application
-
> [EX] Make ActorId and JobId unique in Application table

- apps/api/src/modules/job/application/application.controller.ts
- apps/api/src/modules/job/application/application.module.ts
- apps/api/src/modules/job/application/application.repository.ts
- apps/api/src/modules/job/application/application.service.spec.ts
- apps/api/src/modules/job/application/application.service.ts
- apps/api/src/modules/resume/resume.module.ts
- packages/dtos/src/application.ts
-add endpoint for applyJob
- login as actor 
- check exist resume or create new one
- try to test apply job
> [80] Implement actor apply jobs API @POST

- apps/api/src/modules/report/report.repository.ts
- apps/api/src/modules/report/report.service.spec.ts
- apps/api/src/modules/report/report.service.ts
- added jobTitle to getReports and removed createdAt field from individual reports
- login on swagger
- use the get reports API with arbitrary jobID between 1-10
> [123] Implement get report API @GET

- apps/web/src/common/components/FormController/index.tsx
- apps/web/src/common/components/FormController/types.ts
- apps/web/src/common/components/Navbar/hooks/useNavMenu/index.tsx
- apps/web/src/common/components/UploadFile/hooks/useUploadFile/index.test.ts
- apps/web/src/common/components/UploadFile/hooks/useUploadFile/index.ts
- apps/web/src/common/components/UploadFile/index.test.tsx
- apps/web/src/common/components/UploadFile/index.tsx
- apps/web/src/common/components/UploadFile/types.ts
- apps/web/src/common/utils/file/index.ts
- apps/web/src/modules/profile/edit/actor/constants.ts
- apps/web/src/modules/profile/edit/actor/hooks/useEditActorForm/index.tsx
- apps/web/src/modules/profile/edit/actor/resume/components/ResumeSlot/components/ResumeEdit/hooks/useResumeForm/index.tsx
- apps/web/src/modules/profile/edit/actor/resume/components/ResumeSlot/components/ResumeEdit/index.tsx
- apps/web/src/modules/profile/edit/actor/resume/components/ResumeSlot/components/ResumeEdit/types.ts
- apps/web/src/modules/profile/edit/actor/resume/components/ResumeSlot/types.ts
- apps/web/src/modules/profile/edit/actor/resume/hooks/index.tsx
- apps/web/src/modules/profile/edit/casting/constants.ts
- apps/web/src/modules/profile/edit/casting/hooks/useEditCastingForm/index.tsx
- apps/web/src/modules/rejected/actor/hooks/useActorForm/index.ts
- apps/web/src/modules/signup/actor/hooks/useActorForm/index.ts
- apps/web/src/modules/signup/casting/hooks/useCastingForm/index.ts
- Implement file uploading to S3 for 
- Edit casting profile image
- Edit actor profile image
- Add resume
- Add resume
- Please login as any `actor` first
- Go to https://dev.modela.miello.dev/profile/resume
- Click `เพิ่มเรซูเม่` and add file
- Edit actor / casting profile image
- Please login as any `actor` or `casting` first
- Go to https://dev.modela.miello.dev/profile/edit
> [67][86][89][113] Implement file uploading to S3

- apps/web/src/modules/job/report/components/JobReportCard/hooks/useReport/index.ts
- apps/web/src/modules/job/report/components/JobReportCard/index.tsx
- apps/web/src/modules/job/report/hooks/useGetReport/index.ts
- apps/web/src/modules/job/report/pages/index.tsx
- connect to jobs/reports, job/reports/accept and reject API
- https://dev.modela.miello.dev/job/11/reports (login as admin)
> [122][125][128] connect report UI to API

- apps/web/src/modules/job/apply/components/SelectResume/index.tsx
- apps/web/src/modules/job/apply/components/SelectResume/styled.ts
- apps/web/src/modules/job/apply/components/SelectResume/types.ts
- apps/web/src/modules/job/apply/pages/hooks/index.ts
- apps/web/src/modules/job/apply/pages/index.tsx
- apps/web/src/modules/job/apply/pages/styled.ts
- apps/web/src/modules/job/components/JobCardFooter/index.tsx
- apps/web/src/modules/job/components/JobCardFooter/types.ts
- apps/web/src/modules/job/detail/components/JobCard/index.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/components/JobCard/index.tsx
- apps/web/src/pages/job/[jobId]/apply.tsx
- Add actor apply page, actor is able to apply job by choosing a resume with dropdown
- link apply button in JobCardFooter to actor apply page
- Add jobId as number type in FooterProps type.ts
- Login with actor
- Choose a job to apply
- Choose resume and click "apply"
- If you already apply to this job, an error snackbar will popup with text "คุณได้สมัครงานนี้ไปแล้ว"
- Else, a success snack bar will popup with text "การสมัครเสร็จสิ้น" and post data to backend
- no unit test
> [79] Implement actor apply jobs UI

- apps/web/src/modules/job/detail/components/JobCard/index.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/components/JobCard/index.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/index.tsx
- apps/web/src/modules/profile/show/myProfile/index.tsx
- ![image](https://user-images.githubusercontent.com/73303542/224742448-05416d2e-92e6-474b-9474-f30f24ac440b.png)
- ![image](https://user-images.githubusercontent.com/73303542/224742504-6fb6ef9d-e8fc-4468-8ca8-288f3ad831b3.png)
- Not show jobCard when job is already applied
- Use actor 3-9
> [8] Fix applied job page

- apps/web/src/common/components/Navbar/hooks/useNavMenu/index.tsx
- apps/web/src/common/context/LayoutContext/types.ts
- apps/web/src/modules/job/list/pages/AdminPage/index.tsx
- apps/web/src/modules/job/report/components/JobReportCard/hooks/useReport/index.ts
- ~930 px พังหน่อย แต่ช่างมันเถอะครับ
- https://dev.modela.miello.dev/job (login as admin)
> [EX] Implement admin navbar

- .github/workflows/sonarqube.yml
- Add github actions for sonarqube code scanner which should be run "manually"
-
> [EX] Add sonarqube action

- apps/api/src/app/app.module.ts
- apps/api/src/modules/credit/credit.controller.ts
- apps/api/src/modules/credit/credit.module.ts
- apps/api/src/modules/credit/credit.repository.ts
- apps/api/src/modules/credit/credit.service.spec.ts
- apps/api/src/modules/credit/credit.service.ts
- implement get unpaid job API with unit test
- only unpaid job that is in SELECTION_END status will be shown
- login as casting
- https://api-dev.modela.miello.dev/swagger#/credits/CreditController_getUnpaidJob
> [197] Get unpaid job API

- apps/api/src/app/app.module.ts
- apps/api/src/modules/debit/debit.controller.ts
- apps/api/src/modules/debit/debit.module.ts
- apps/api/src/modules/debit/debit.repository.ts
- apps/api/src/modules/debit/debit.service.spec.ts
- apps/api/src/modules/debit/debit.service.ts
- implement mark actor transaction with unit test
- login as admin
- go to https://api-dev.modela.miello.dev/swagger#/debits/DebitController_markAsPaid
> [201] Mark actor transaction

- apps/api/src/app/app.module.ts
- apps/api/src/modules/notification/constants.ts
- apps/api/src/modules/notification/notification.controller.ts
- apps/api/src/modules/notification/notification.module.ts
- apps/api/src/modules/notification/notification.repository.ts
- apps/api/src/modules/notification/notification.service.spec.ts
- apps/api/src/modules/notification/notification.service.ts
- packages/dtos/src/notification.ts
- Implement get notification API with query and pagination and auto mark as read
- login as casting and actor
- go to https://api-dev.modela.miello.dev/swagger#/notifications/NotificationController_getNotifications
> [177,178,181] Implement get notification API

- apps/api/src/modules/credit/credit.controller.ts
- apps/api/src/modules/credit/credit.repository.ts
- apps/api/src/modules/credit/credit.service.ts
- packages/database/prisma/dbml/schema.dbml
- packages/database/prisma/migrations/20230324044618_add_amount_to_credit/migration.sql
- packages/database/prisma/migrations/20230324045410_change_evidence_url_to_proof_url/migration.sql
- packages/database/prisma/schema.prisma
- packages/database/src/mocks/getBaseMock/index.ts
- packages/dtos/index.ts
- packages/dtos/src/credit.ts
- change schema for Credit by add amount
- change evidenceUrl to proofUrl in database
- create endpoint GET /credits for admin 
-
> [165] Implement casting transaction list @GET

- apps/api/src/modules/notification/constants.ts
- apps/api/src/modules/notification/notification.controller.ts
- add Receive_offer query in constraint
- change type in swagger
-
> [177,181] fix: Implement notification API @GET

- apps/api/src/app/app.module.ts
- apps/api/src/modules/job/application/application.repository.ts
- apps/api/src/modules/job/application/offer/offer.controller.ts
- apps/api/src/modules/job/application/offer/offer.module.ts
- apps/api/src/modules/job/application/offer/offer.repository.ts
- apps/api/src/modules/job/application/offer/offer.service.ts
-implement the API which allows casting to send job offer and mark the application as `OFFER_SENT`.
- go to swagger
- login as actor and apply for a job
- use lib:studio to see if the application has been created
- login as casting of the respective job and use the new offer API to send offer using the same `actorId` and `jobId`.
- check in prisma studio again if the application status is now `OFFER_SENT`
- try using the api with exact same parameter again, it should become a bad request
- try using arbitrary jobId and see if it's a 404 or forbidden due to not being owner
- try using arbitrary actorId and see if it's a bad request (actor has not applied)
> [134] Implement send job offer API @POST

- apps/api/src/modules/debit/debit.controller.ts
- apps/api/src/modules/debit/debit.repository.ts
- apps/api/src/modules/debit/debit.service.ts
- packages/dtos/index.ts
- packages/dtos/src/debit.ts
- add debit dto for new endpoint
- add endpoint ```GET /debits/jobs``` for admin to get all job that have pending actor debit 
- add endpoint ```GET /debits/jobs/:jobId/actors``` for admin to get all pending actor debit for each job
- login as any admin
- https://api-dev.modela.miello.dev/swagger#/debits/DebitController_getPendingJobsDebits
- should get all job that have pending actor debit 
- https://api-dev.modela.miello.dev/swagger#/debits/DebitController_getPendingDebitsByJobId
- use jobId from above to get all pending actor debit for that job
- if not any jobs that have debits, go edit in dev database or by casting
- about JobStatus flow: only FINISHED job will be check for pending debit for actor?
- not have unit …
> [168] Implement actor with pending transaction list API @GET

- apps/api/src/modules/job/application/offer/offer.controller.ts
- apps/api/src/modules/job/application/offer/offer.module.ts
- apps/api/src/modules/job/application/offer/offer.service.ts
- apps/api/src/modules/notification/notification.module.ts
- Implemented API endpoint to allow actor to accept job offers sent by the casting
- login as actor on swagger
- create a job application
- login as casting of the respective job or use prisma studio to change `ApplicationStatus` to `OFFER_SENT`
- use the accept/reject API with id of the respective `JOB` (not `APPLICATION`!)
- see in prisma studio if it is successful
- try using the same API again, it should become a bad request.
- try using arbitrary `jobId`, it should be a "haven't applied to this job" or "not found"
> [141][144] Implement accept/reject job offer API @PUT

- apps/api/src/modules/notification/notification.module.ts
- apps/api/src/modules/report/report.module.ts
- apps/api/src/modules/report/report.repository.ts
- apps/api/src/modules/report/report.service.spec.ts
- apps/api/src/modules/report/report.service.ts
- notify casting when their job is cancelled
- notify actor when job that they applied is cancelled
-
> [186] [187] Connect get admin cancel service with notification service

- apps/api/src/modules/debit/debit.repository.ts
- apps/api/src/modules/job/application/offer/offer.service.ts
- apps/api/src/modules/notification/constants.ts
- apps/api/src/modules/notification/notification.repository.ts
- packages/database/prisma/dbml/schema.dbml
- packages/database/prisma/migrations/20230325155802_change_relation_for_noti_credit_refund/migration.sql
- packages/database/prisma/schema.prisma
- packages/database/src/mocks/getBaseMock/index.ts
- packages/dtos/src/notification.ts
- edit database schema for Notification by remove actorId and refundId to applicationId
- edit database schema for Credit and Refund by make jobId and applicationId unique in order
- fix query constraints for notification
- fix debit repository and offer service that have been affected
- make get notifications now contain notificationId and applicationStatus for user
-
> [132] Edit Database Schema

- apps/api/src/modules/credit/credit.controller.ts
- apps/api/src/modules/credit/credit.module.ts
- apps/api/src/modules/credit/credit.repository.ts
- apps/api/src/modules/credit/credit.service.ts
- apps/api/src/modules/job/job.repository.ts
- add service for accept and reject credit transaction
- go to https://api-dev.modela.miello.dev/swagger#/credits and test with admin account
> [159] [199] Implement accept-reject credit transaction API @PUT

- apps/api/src/modules/notification/notification.repository.ts
- apps/api/src/modules/refund/refund.controller.ts
- apps/api/src/modules/refund/refund.repository.ts
- apps/api/src/modules/refund/refund.service.ts
- packages/dtos/index.ts
- packages/dtos/src/refund.ts
- Implement pending refund list API
- Implement request refund API
- using admin account to see pending refund list
- using casting account to request refund for actor that have application in job
> [156] [162] Implement request refund API & Implement pending refund list API

- apps/api/src/modules/credit/credit.controller.ts
- apps/api/src/modules/credit/credit.repository.ts
- apps/api/src/modules/credit/credit.service.ts
- apps/api/src/modules/job/job.repository.ts
- packages/dtos/src/credit.ts
- get transaction detail API
- send proof of transaction API
- login as casting and get jobid from job that selection ended
- using jobId to get detail at https://api-dev.modela.miello.dev/swagger#/credits/CreditController_getTransactionDetail
- then try to send by using https://api-dev.modela.miello.dev/swagger#/credits/CreditController_sendProofOfTransaction
> [153] Implement send proof of transaction API & get transaction detail API

- apps/api/Dockerfile
- apps/api/src/modules/auth/auth.service.spec.ts
- apps/web/Dockerfile
- Fix lockfile outdated problem which happens in Dockerfile when built
-
> [HOTFIX] Fix pnpm version in dockerfile

- apps/api/src/modules/credit/credit.controller.ts
- apps/api/src/modules/refund/refund.controller.ts
- apps/api/src/modules/refund/refund.module.ts
- apps/api/src/modules/refund/refund.service.spec.ts
- apps/api/src/modules/refund/refund.service.ts
- apps/api/src/modules/user/user.module.ts
- packages/dtos/src/refund.ts
- add swagger type to credit
- add missing endpoint get request refund detail (sorry ;w;)
-  Test here using casting account https://api-dev.modela.miello.dev/swagger#/refunds/RefundController_getRefundInfo
> [156] Implement request refund API

- apps/web/src/common/components/Navbar/hooks/useNavMenu/index.tsx
- apps/web/src/common/context/LayoutContext/types.ts
- apps/web/src/modules/unpaid/components/UnpaidJobCard/UnpaidJobCardFooter/index.tsx
- apps/web/src/modules/unpaid/components/UnpaidJobCard/UnpaidJobCardFooter/styled.ts
- apps/web/src/modules/unpaid/components/UnpaidJobCard/UnpaidJobCardFooter/types.ts
- apps/web/src/modules/unpaid/components/UnpaidJobCard/UnpaidJobCardHeader/index.tsx
- apps/web/src/modules/unpaid/components/UnpaidJobCard/UnpaidJobCardHeader/styled.ts
- apps/web/src/modules/unpaid/components/UnpaidJobCard/UnpaidJobCardHeader/types.ts
- apps/web/src/modules/unpaid/components/UnpaidJobCard/index.tsx
- apps/web/src/modules/unpaid/components/UnpaidJobCard/styled.ts
- apps/web/src/modules/unpaid/hooks/useUnpaidJobData/index.ts
- apps/web/src/modules/unpaid/pages/index.tsx
- apps/web/src/modules/unpaid/pages/styled.ts
- apps/web/src/pages/unpaid/index.tsx
- add UnpaidJobCard
- add unpaid job list on navBar (also focus)
- connect to API 
PS. please login as casting8
-
> [196] unpaid job list UI

- apps/web/src/modules/job/credit/pages/send-proof/hooks/useSendingDetails/index.tsx
- apps/web/src/modules/job/credit/pages/send-proof/index.tsx
- apps/web/src/modules/job/refund/pages/hooks/useRefundForm/index.tsx
- apps/web/src/modules/job/refund/pages/index.tsx
- Connect send proof of transaction to API
- Connect request refunds page to API
- Login as casting 4 account
- Please go to https://dev.modela.miello.dev/job/3/send-proof
- Login as casting 10 account
- Please go to https://dev.modela.miello.dev/job/1/refund/18
> [152][155] Connect send proof of transaction and refund to API

- apps/api/src/modules/job/application/application.module.ts
- apps/api/src/modules/job/job.module.ts
- apps/api/src/modules/job/job.service.spec.ts
- apps/api/src/modules/job/job.service.ts
- apps/api/src/modules/refund/refund.module.ts
- apps/api/src/modules/refund/refund.repository.ts
- added a function in job service which causes all refund associated with a job to be removed when the job's status is changed to FINISHED
- N/A
> [N/A] Implement remove all refunds from finished jobs 

- apps/api/src/modules/job/application/application.controller.ts
- apps/api/src/modules/job/application/application.service.ts
- change from actor can cancel application only job status is selecting to only open
-
> [EX] fix cancel applied job API 

- apps/api/src/modules/job/application/application.repository.ts
- apps/api/src/modules/job/application/application.service.spec.ts
- apps/api/src/modules/job/application/application.service.ts
- apps/api/src/modules/job/job.repository.ts
- apps/api/src/modules/refund/refund.service.ts
- apps/web/src/modules/job/appliedActor/components/ActorCardHeader/index.test.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCardHeader/index.tsx
- packages/dtos/src/application.ts
- packages/dtos/src/job.ts
- fix refund button display logic so that it won't show when job is not refundable
- add `isPaid` to /jobs
- wait for watch tower
> [EX] Fix refund button and add isPaid to /jobs

- apps/web/src/modules/job/appliedJob/components/JobCardContainer/components/CancelAppliedModal/hooks/useCancelAppliedJob.ts
- apps/web/src/modules/job/appliedJob/components/JobCardContainer/components/CancelAppliedModal/index.tsx
- apps/web/src/modules/job/appliedJob/components/JobCardContainer/components/CancelAppliedModal/styled.ts
- apps/web/src/modules/job/appliedJob/components/JobCardContainer/components/CancelAppliedModal/types.ts
- apps/web/src/modules/job/appliedJob/components/JobCardContainer/components/JobCard/index.tsx
- apps/web/src/modules/job/components/JobCardFooter/index.tsx
- apps/web/src/modules/job/components/JobCardFooter/types.ts
- Implement cancel job button in JobCardFooter
- Add confirmation modal
- https://dev.modela.miello.dev/job/applied
- log in as actor2@gmail.com
> [149] Cancel applied job UI

- apps/web/src/common/components/Navbar/components/NavbarDesktop/styled.ts
- apps/web/src/modules/job/appliedJob/components/JobCardContainer/components/JobCard/index.tsx
- apps/web/src/modules/job/appliedJob/components/SearchBox/index.tsx
- apps/web/src/modules/job/components/JobCardFooter/index.tsx
- apps/web/src/modules/job/components/JobCardHeader/index.tsx
- apps/web/src/modules/job/components/JobForm/components/AddShootingButton/index.tsx
- apps/web/src/modules/job/components/JobForm/components/ShootingForm/index.tsx
- apps/web/src/modules/job/detail/components/JobCard/components/ShootingDetail/index.tsx
- apps/web/src/modules/job/detail/components/JobCard/index.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/components/JobCard/index.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/index.tsx
- apps/web/src/modules/job/list/components/SearchBox/index.tsx
- apps/web/src/modules/job/report/components/JobReportCard/index.tsx
- apps/web/src/modules/report/pages/index.tsx
- apps/web/src/modules/unpaid/components/UnpaidJobCard/UnpaidJobCardFooter/index.tsx
- apps/web/src/modules/unpaid/components/UnpaidJobCard/UnpaidJobCardHeader/index.tsx
- apps/web/src/modules/unpaid/components/UnpaidJobCard/index.tsx
- Change all "prop" to "props"
-
> [EX] Change typo from props to prop

- apps/web/src/common/context/SnackbarContext/index.tsx
- apps/web/src/common/context/SnackbarContext/styled.ts
- apps/web/src/modules/profile/show/myProfile/index.tsx
- refactor condition in myProfile
- add border to snackbar
- ![image](https://user-images.githubusercontent.com/73303542/229420779-35077a58-abac-444c-89d0-48e01643e959.png)
- Edit job of casting 6 in dev
> [Extra] refactor condition in myProfile, add border to snackbar

- apps/web/src/common/components/MenuBar/styled.ts
- apps/web/src/modules/job/appliedActor/components/ActorFilter/index.tsx
- apps/web/src/modules/job/appliedActor/pages/styled.ts
- apps/web/src/modules/job/appliedJob/pages/index.tsx
- apps/web/src/modules/job/appliedJob/pages/styled.ts
- apps/web/src/modules/job/components/JobMenu/styled.ts
- apps/web/src/modules/job/list/components/FilterContainer/styled.ts
- apps/web/src/modules/job/list/pages/ActorCastingPage/index.tsx
- apps/web/src/modules/job/list/pages/ActorCastingPage/styled.ts
- apps/web/src/modules/job/list/pages/AdminPage/index.tsx
- apps/web/src/modules/job/list/pages/AdminPage/styled.ts
- apps/web/src/modules/notification/pages/index.tsx
- apps/web/src/modules/notification/pages/styled.ts
- add position:sticky to
- menubar
- filter in job list page (both ActorCasting and admin page)
- filter in applied actor page
- filter in applied job page
- filter in notification page
ไม่รู้ตกอันไหนไปอีกรึเปล่า ฝากเช็คที
- https://dev.modela.miello.dev/ (wait for watchtower)
> [fix] Made menubar/filter sticky

- apps/api/src/modules/job/job.repository.ts
- apps/api/src/modules/job/job.service.spec.ts
- apps/api/src/modules/job/job.service.ts
- apps/web/src/modules/job/components/JobMenu/hooks/useSummaryData/index.ts
- apps/web/src/modules/job/components/JobMenu/index.tsx
- packages/dtos/src/application.ts
- packages/dtos/src/auth.ts
- packages/dtos/src/info.ts
- packages/dtos/src/job.ts
- packages/dtos/src/notification.ts
- packages/dtos/src/refund.ts
- packages/dtos/src/user.ts
- Add text and disable button when job is not paid and status is selection ended
- add enum and type to dtos
- wait for watchtower
> [EX] Prevent finishing job when job is not paid yet + Enum Docs fix

- apps/web/src/modules/job/list/pages/ActorCastingPage/index.tsx
> fix: fix create job button

- apps/web/src/modules/rejected/pages/hooks/useInitialData/index.ts
- packages/database/src/mocks/mock/index.ts
> [EX] fix await and map bug

- apps/web/src/modules/rejected/actor/hooks/useActorForm/index.ts
- apps/web/src/modules/rejected/casting/hooks/useCastingForm/index.ts
- apps/web/src/modules/signup/actor/hooks/useActorForm/index.ts
- apps/web/src/modules/signup/casting/hooks/useCastingForm/index.ts
- Fix register form and rejected form that send undefined for optional field
- https://dev.modela.miello.dev/signup/actor
- https://dev.modela.miello.dev/signup/casting
> [EX] Fix form that send undefined when submit

- apps/web/src/modules/job/list/pages/ActorCastingPage/hooks/useJobListData/index.ts
- apps/web/src/modules/job/list/pages/AdminPage/hooks/useJobListData/index.ts
- apps/web/src/modules/notification/pages/hooks/useNotiListData/index.ts
- Nothing change in UI
- Affect if you load more than 10 jobs (Some times)
> [EX] fix infinite scroll page counter increase

- apps/api/src/modules/credit/credit.service.ts
- apps/api/src/modules/job/application/application.controller.ts
- apps/api/src/modules/job/application/application.repository.ts
- apps/api/src/modules/job/application/application.service.ts
- packages/database/prisma/dbml/schema.dbml
- packages/database/prisma/migrations/20230410071447_add_rating_in_application/migration.sql
- packages/database/prisma/schema.prisma
- packages/dtos/src/application.ts
- add rating field in database
- make endpoint post rating
- edit amount in credit details for profits
- test in swagger log in as casting with finish job and have actor
-  https://api-dev.modela.miello.dev/swagger#/application/ApplicationController_rateActor
> [EX] Implement rate actor for job

- apps/api/src/modules/job/job.repository.ts
- packages/dtos/src/job.ts
- pnpm-lock.yaml
- add isPaid in GetJobCardDto
- add isPaid query from the field of job in database at ```GET /jobs``` by casting
- add isPaid query from the field of job in database at ```GET /jobs/applied``` by actor
- add isPaid query from the field of job in database at ```GET /jobs/admin``` by admin (not used in front? but it's extended dto)
- assumed the field isPaid of job table in database is correct
- login as casting (maybe casting4)
- https://api-dev.modela.miello.dev/swagger#/jobs/JobController_findAll
- should see isPaid of each job
- login as actor (maybe actor2)
- https://api-dev.modela.miello.dev/swagger#/jobs/JobController_findAllApplied
- should …
> [EX] add isPaid for get jobs

- apps/web/src/modules/job/components/JobCardHeader/index.tsx
- apps/web/src/modules/job/components/JobCardHeader/types.ts
- apps/web/src/modules/job/list/components/JobCardContainer/components/JobCard/types.ts
- add icons to casting job page and actor applied job page (also add Tooltip to the icons)
for casting use casting8 and also filter jobs that is not opened
for actor  use actor4 and filter offer accepted jobs
PS. I'm using dev API 
-
> [EX] add paid/unpaid icons

- apps/api/src/modules/job/application/application.repository.ts
- apps/api/src/modules/user/profile/profile.repository.ts
- apps/api/src/modules/user/user.repository.ts
- packages/dtos/src/application.ts
- packages/dtos/src/job.ts
- packages/dtos/src/profile.ts
- Add rating to Job History endpoint (null value if there is no review yet)
- Add rating to Profile endpoint (null value if there are no reviews)
- Add rating to AppliedActor endpoint (undefined when job is not in finish status)
~~(Unit Test will be fixed after open PR around 1 - 2 hours)~~
- To test rating in Job History page
https://api-dev.modela.miello.dev/swagger#/users/UserController_getUsersWorkHistory
1. Login as actor4 account
2. Request with userId 14
3. Expected rating null in jobId 3
- To test rating in Profile endpoint
https://api-dev.modela.miello.dev/swagger#/profile/ProfileController_getProfileById
1. Login as actor4 account
2. Request with userId 14
3. Should see review field.
- To test rating in AppliedActor endpoint …
> [EX] Add rating field to endpoint related to job and profile

- apps/api/src/modules/credit/credit.repository.ts
- apps/api/src/modules/credit/credit.service.ts
- apps/api/src/modules/job/application/application.service.spec.ts
- apps/api/src/modules/job/application/application.service.ts
- apps/api/src/modules/job/application/offer/offer.service.ts
- packages/database/prisma/dbml/schema.dbml
- packages/database/prisma/migrations/20230416055148_change_amount_to_decimal/migration.sql
- packages/database/prisma/schema.prisma
- packages/dtos/src/credit.ts
- Fix decimal error in database
- Add guard condition when job in selecting phase
- Test decimal value
https://api-dev.modela.miello.dev/swagger#/credits/CreditController_getPendingTransactions
1. Login as Casting 1
2. Send proof of transaction for job id 13 
- Test guard condition
https://api-dev.modela.miello.dev/swagger#/offer
https://api-dev.modela.miello.dev/swagger#/application/ApplicationController_rejectApplication
1. Test on job id 9, casting 6 account (this job is in `SELECTING` state)
- After this PR, it might cause floating-point error in `amount` field so we might need to add `toFixed` to slice only 2 decimal point
> [EX] Add guard condition for selecting job and fix decimal value in database

- apps/web/src/modules/profile/show/components/ActorProfileInfo/index.tsx
- apps/web/src/modules/profile/show/components/CastingProfileInfo/index.tsx
- ![image](https://user-images.githubusercontent.com/73303542/232288078-838f63c3-06c7-4f2d-89a3-bde721dce5ee.png)
- https://dev.modela.miello.dev/profile
> [EX] center edit profile button in profile page

- apps/web/src/common/components/JobCard/JobCardFooter/RatingFooter/index.tsx
- apps/web/src/common/components/JobCard/JobCardFooter/RatingFooter/styled.ts
- apps/web/src/common/components/JobCard/JobCardFooter/RatingFooter/types.ts
- apps/web/src/common/components/JobCard/constants.ts
- apps/web/src/common/components/JobCard/types.ts
- apps/web/src/modules/job/appliedActor/components/ActorCard/index.test.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCard/index.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCard/styled.ts
- apps/web/src/modules/job/appliedActor/components/ActorCardHeader/index.test.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCardHeader/index.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCardReview/hooks/useReview/index.ts
- apps/web/src/modules/job/appliedActor/components/ActorCardReview/index.tsx
- apps/web/src/modules/job/appliedActor/components/ActorCardReview/styled.ts
- apps/web/src/modules/job/appliedActor/components/ActorCardReview/types.ts
- apps/web/src/modules/job/appliedActor/components/ResumeDownloadButton/index.tsx
- apps/web/src/modules/job/appliedActor/components/ResumeDownloadButton/styled.ts
- apps/web/src/modules/job/appliedActor/components/ResumeDownloadButton/types.ts
- apps/web/src/modules/job/appliedActor/pages/hooks/useFilter/index.ts
- apps/web/src/modules/job/components/JobMenu/index.tsx
- apps/web/src/modules/job/list/components/JobCardContainer/utils.ts
- apps/web/src/modules/notification/components/NoticardContainer/components/NotiCard/Components/NotiCardFooter/index.tsx
- apps/web/src/modules/profile/show/components/ActorProfileInfo/index.tsx
- apps/web/src/modules/profile/show/components/ActorProfileInfo/styled.ts
- apps/web/src/modules/profile/show/components/ActorProfileInfo/types.ts
- apps/web/src/modules/transaction/pages/casting/components/PendingCastingCard/index.tsx
- Implement actor rating (job must be FINISHED)
- view rating in profile
- view rating in history page
- remove default filter in applied actor page (also remove มีนักแสดงรออยู่... คน when the status is not pending or selecting)
- add profile in pending transaction page
- add new text when actor doesn't accept/reject offer within time
- only show send offer button when job status is selecting
-
> [Ex] Actor Rating & Misc
