2110336-2565-2/sec2-group9-modela

apps/api/src/modules/job/job.controller.ts, apps/api/src/modules/job/job.service.spec.ts, apps/api/src/modules/job/job.service.ts
- implement the ```GET job/```  with ```castingId``` params
- write unit test for ```GET job/``` with ```castingId``` params with user type ```actor``` and ```casting```
- https://api-dev.modela.miello.dev/swagger#/job/JobController_findAll
- login at ```POST auth/login``` with username: ```ayame@hololive.com```, password: ```ayame123```
- try ```GET job/``` with limit:1 (for easier count total job card by maxPage) , page:1 , castingId: from 20 to 30 (the mocked database have jobs's castingId within this range)
=> [19][21] Implement and write unit test for get job by castingId

apps/api/src/modules/job/job.controller.ts, apps/api/src/modules/job/job.repository.ts, apps/api/src/modules/job/job.service.spec.ts, apps/api/src/modules/job/job.service.ts, packages/dtos/src/job.ts
- Implemented edit job feature
- also includes both successful and forbidden test units
- fixed a few bugs/unused code from post-job as well
- login into service as caster
```
register
{
"email": "ayame@hololive.com",
"password": "ayame123",
"firstName": "Ayame",
"lastName": "Nakiri",
"prefix": "Mrs.",
"nationality": "Japanese",
"ssn": "1212312121",
"gender": "FEMALE",
"phoneNumber": "0123456789",
"idCardImageUrl": "hololive.com"
}
login
{
"email": "yagoo@hololive.com",
"password": "yagoo123"
}
```
- post job
- put job with the following
```
sample edit
{
"title": "NEW UPDATE",
"description": "IT WORKS",
"status": "OPEN",
"role": "WORKS",
"minAge": 1,
"maxAge": 5,
"gender": "ANY",
"actorCount": 1,
"wage": 555555,
"applicationDeadline": "2024-02-11T17:42:50.556Z",
"shooting": [
{ …
```
=> [33] Implement edit job API @PUT

apps/api/src/modules/job/job.service.spec.ts, apps/api/src/modules/job/job.service.ts, packages/dtos/src/job.ts
- make jobs that do not have shooting visible when not filtered
- set new bound for max and min integer for wage and age from 0 to 2147483647
- ignore the timezone of ISO format startTime and endTime when querying
- age and wage or any number (maybe?) that are "Int" in the database schema can only handle Int32 (+-2147483647)
- ignore the timezone corresponding to database
- https://dev.modela.miello.dev/ (login first)
- search job using startTime from 13:00 to 16:00  should see the "test 13:00 to 16:00" job 
- should see "not have shooting" job's title
=> [19] fix job search

apps/api/src/modules/user/user.controller.ts, apps/api/src/modules/user/user.repository.ts, apps/api/src/modules/user/user.service.ts, apps/web/src/common/context/UserContext/hooks/useUserData/index.test.tsx, apps/web/src/common/context/UserContext/hooks/useUserData/index.ts, packages/dtos/src/user.ts
- add ```PendingUserDto``` and ```UpdateUserStatusDto``` in user Dto
- implement ```GET /users/pending``` to get all users that have PENDING status
- show the oldest first and have essential data for each user type
- implement ```PUT /users/:id/verification``` for update a user status to ACCEPTED, or REJECTED with rejectedReason
- both endpoints need to be admin only to access, else will be a Forbidden response.
- https://api-dev.modela.miello.dev/swagger#/auth/AuthController_login 
- login with email: ```admin1@gmail.com``` and password: ```password```
- https://api-dev.modela.miello.dev/swagger#/users/UserController_getUserData
- get pending users to inspect all users that have PENDING status
- https://api-dev.modela.miello.dev/swagger#/users/UserController_updateUserStatus
- choose …
=> [93][96][99][105][108] Implement get pending registration and accept and reject actor's registration API

apps/web/src/common/components/FormController/components/UploadFile/index.tsx, apps/web/src/common/components/FormController/components/UploadFile/types.ts, apps/web/src/common/components/FormController/index.test.tsx, apps/web/src/common/components/FormController/index.tsx, apps/web/src/common/components/FormController/types.ts, apps/web/src/modules/job/components/JobForm/components/ShootingForm/constant.ts, apps/web/src/modules/job/components/JobForm/components/ShootingForm/index.tsx, apps/web/src/modules/job/components/JobForm/constant.ts, apps/web/src/modules/job/components/JobForm/index.tsx, apps/web/src/modules/login/constants.ts, apps/web/src/modules/login/index.tsx, apps/web/src/modules/profile/edit/casting/constants.ts, apps/web/src/modules/profile/edit/casting/hooks/useEditCastingForm/index.tsx, apps/web/src/modules/profile/edit/casting/hooks/useEditCastingForm/schema.ts, apps/web/src/modules/profile/edit/casting/index.test.tsx, apps/web/src/modules/profile/edit/casting/index.tsx, apps/web/src/modules/profile/edit/casting/styled.ts, apps/web/src/modules/profile/edit/pages/index.tsx, apps/web/src/modules/rejected/actor/constants.ts, apps/web/src/modules/rejected/actor/index.tsx, apps/web/src/modules/signup/actor/constants.ts, apps/web/src/modules/signup/actor/index.tsx, apps/web/src/modules/signup/casting/constants.ts, apps/web/src/modules/signup/casting/index.tsx, apps/web/src/pages/profile/edit.ts
- Implement profile edit for casting page
- Refactor FormController to be more type strict
- Login as one of `Casting` account
- https://dev.modela.miello.dev/profile/edit
- This PR does not implement Upload image yet
=> [89] Implement casting profile edit page

apps/api/src/app/app.module.ts, apps/api/src/modules/resume/resume.controller.ts, apps/api/src/modules/resume/resume.module.ts, apps/api/src/modules/resume/resume.respository.ts, apps/api/src/modules/resume/resume.service.spec.ts, apps/api/src/modules/resume/resume.service.ts, packages/dtos/index.ts, packages/dtos/src/resume.ts
- Implemented POST resume API
```
{
"name": "test resume v1",
"resumeUrl": "google.com"
}
```
The above should work provided that you are properly logged into a verified actor account.
I suggest slightly modifying to make a v2 and trying again to see if it properly appends.
```
{
"name": "test resume v3",
"resumeUrl": "thisisnotaurl"
}
```
The above should raise a bad request exception due to the url being invalid.
=> [114] Implement actor create resumes API @POST

apps/api/src/modules/job/job.controller.ts, apps/api/src/modules/job/job.repository.ts, apps/api/src/modules/job/job.service.ts, packages/dtos/src/job.ts
- implement ```GET /jobs/admin``` endpoint for admin to get reported jobs and filtering
- login with (or any admin)
```
{
"email": "admin1@gmail.com",
}
```
- https://api-dev.modela.miello.dev/swagger#/jobs/JobController_findAllByAdmin
- try get jobs with ```REPORTED``` status query on along with any others filters
- should see all reported jobs indicated by boolean ```isReported``` field in each jobs
=> [71] Implement get jobs for admin API @GET

apps/api/src/modules/job/job.controller.ts, apps/api/src/modules/job/job.repository.ts, apps/api/src/modules/job/job.service.ts, packages/dtos/src/job.ts
- Implement  ```PUT /jobs/:id/status``` endpoint for casting to update job's status
- Limit the jobs that have JobStatus FINISHED, CANCELLED can't update JobStatus
- login with (or any casting)
```
{
"email": "casting2@gmail.com",
}
```
- https://api-dev.modela.miello.dev/swagger#/jobs/JobController_findAll
- get all jobs that the casting own (also select OPEN, CLOSE status to view all jobs)
- https://api-dev.modela.miello.dev/swagger#/jobs/JobController_updateStatus
- update job's status to OPEN, SELECTING, SELECTION_ENDED, FINISHED, CANCELLED
- repeat get all jobs and update again
- also try with jobs that not own and from other roles
- can it update skipped order of …
=> [77] Implement change job's status API @PUT

apps/api/src/modules/job/job.service.ts
- fix  ```GET /jobs/admin``` endpoint for admin to get reported jobs and filtering
- when only query for reported jobs, will apply the default search of JobStatus (['OPEN'])
- should see only OPEN jobs when only query for reported jobs
- login with (or any admin)
```
{
"email": "admin1@gmail.com",
}
```
- https://api-dev.modela.miello.dev/swagger#/jobs/JobController_findAllByAdmin
- try get jobs with ```REPORTED``` status query on along with any others filters
- should see all reported jobs indicated by boolean ```isReported``` field in each jobs
=> [71] fix get jobs for admin API @GET

apps/api/src/modules/user/profile/profile.controller.ts, apps/api/src/modules/user/profile/profile.repository.ts, apps/api/src/modules/user/profile/profile.service.ts, packages/dtos/src/profile.ts
- implement ```GET /profile/:id``` endpoint for user to get user's profile
- create new related Dto
- login with (or any actor)
```
{
"email": "actor6@gmail.com",
}
```
- https://api-dev.modela.miello.dev/swagger#/profile/ProfileController_getProfileById
- get any actor's (11-20) or casting (21-30) profile by Id
- not sure this Endpoint can be use for casting to view actor's profile only or vice versa or actor view actor or casting view casting
- according to user's story casting view actor
- according to draft API's Endpoint both can view
=> [83] Implement get profile API @GET

apps/api/src/modules/job/job.controller.ts, apps/api/src/modules/job/job.repository.ts, apps/api/src/modules/job/job.service.ts, packages/dtos/src/job.ts
- implement ```GET /jobs/applied``` endpoint for actor to get applied jobs and filtering
- only able to filter title, jobStatus and applicationStatus
- title is sub-string search, insensitive case
- if not send any parameters (according to design)
- jobStatus will be ['PENDING']
- applicationStatus will be ['OPEN','SELECTING',''SELECTION_END']
- title will be undefined (search any title)
- login with (or any actor)
```
{
"email": "actor6@gmail.com",
}
```
- https://api-dev.modela.miello.dev/swagger#/jobs/JobController_findAllApplied
- try get jobs with any jobStatus and applicationStatus combination
- should see all jobs and applicationStatus of the actor
=> [68] Implement get applied jobs API @GET

apps/api/src/modules/job/job.repository.ts, packages/dtos/src/job.ts
- fix ```GET /jobs/applied``` endpoint for actor to get applied jobs and filtering
- change the type of appliedStatus in GetAppliedJobDto from JobStatus to ApplicationStatus 
- should see the correct type and example in swagger like this ("appliedStatus" should be "PENDING")
```
[
{
"title": "string",
"description": "string",
"gender": "string",
"actorCount": 0,
"wage": 0,
"applicationDeadline": "2023-02-26T13:24:05.450Z",
"jobId": 0,
"companyName": "string",
"jobCastingImageUrl": "string",
"castingId": 0,
"castingName": "string",
"status": "string",
"appliedStatus": "PENDING"
}
]
```
- login with (or any actor)
```
{
"email": "actor6@gmail.com",
}
```
- …
=> [68] fix type in get applied jobs API @GET

apps/api/src/modules/job/job.controller.ts, apps/api/src/modules/job/job.repository.ts, apps/api/src/modules/job/job.service.spec.ts, apps/api/src/modules/job/job.service.ts, packages/dtos/src/job.ts
- add ```isApplied``` boolean field for each jobs in ```GET /jobs``` endpoint for when GET by actor 
- should see isApplied field for each jobs when query by actor
- login with any actor
- https://api-dev.modela.miello.dev/swagger#/jobs/JobController_findAll
- try get jobs with ```OPEN``` and ```CLOSE``` status  query to view all jobs
- should see some jobs that ```isApplied``` is ```true``` means an actor already applied that job //in front end "สมัครงาน" Button should disappear
=> [EX] add isApplied when get jobs by actor

apps/api/src/modules/job/job.repository.ts, apps/api/src/modules/job/job.service.ts, apps/api/src/modules/report/report.repository.ts, apps/api/src/modules/user/profile/profile.controller.ts, apps/api/src/modules/user/profile/profile.service.ts
- endpoint ```GET /profiles/:id``` add a feature that the same role can't view each other
- endpoint ```PUT /jobs/:id/status```
- add ForbiddenException when change JobStatus is not in order
- change ApplicationStatus of application in the job when changing JobStatus
- https://dev.modela.miello.dev/
- login with any casting in one window
- login with actor that has resumes (maybe 1,2) in another window
- as casting create new job
- as actor apply that created job
- as casting change that JobStatus in order until "เสร็จสิ้นการคัดเลือก" (SELECTION_END)
- any pending actors will automatically change ApplicationStatus to "ไม่ผ่านการคัดเลือก" (REJECTED)
- also admin cancell job will change to REJECTED
=> [77] add feature in change job's status API @PUT

apps/api/src/modules/job/job.repository.ts, apps/api/src/modules/job/job.service.spec.ts, apps/api/src/modules/job/job.service.ts, packages/dtos/src/job.ts
- add ```isApplied``` field in Dto for endpoint ```GET /jobs/:id```
- https://api-dev.modela.miello.dev/swagger
- login as actor 
- try ```GET /jobs/:id``` in https://api-dev.modela.miello.dev/swagger#/jobs/JobController_findOne
- should see isApplied boolean
- try apply to some jobs and see what changed 
- in https://api-dev.modela.miello.dev/swagger#/application/ApplicationController_applyJob
=> [EX] add isApplied in GET /jobs/:id

apps/api/src/modules/resume/resume.controller.ts, apps/api/src/modules/resume/resume.respository.ts, apps/api/src/modules/resume/resume.service.ts
- implemented API endpoint for editing resume
- go to swagger
- login as actor
- create a resume, here's a sample.
```
{
"name": "HELLO PLS UPDATE ME",
"resumeUrl": "google.com"
}
```
- open db:studio to check if the resume is there
- update the resume (the ID should be 11), here's some samples
WORKING
```
{
"name": "updated",
"resumeUrl": "aaaa.com"
}
```
ERROR
```
{
"name": "this should not work",
"resumeUrl": "this is not URL"
}
```
- also try editing other's resume
=> [195] Implement edit resume API @PUT

apps/api/src/modules/job/application/application.controller.ts, apps/api/src/modules/job/application/application.repository.ts, apps/api/src/modules/job/application/application.service.ts
- implemented API which allows actor to cancel (completely delete) application for jobs
- go to swagger and login as caster with application already on prisma studio
- try canceling application with their respective `jobId`
- should be a bad request if haven't applied or job is not searching.
- try arbitrary `jobId` (very high numbers for example) and see if it returns 404 for job not found
- the application should be deleted otherwise.
=> [150] Implement cancel applied job API @PUT

apps/api/src/modules/debit/debit.module.ts, apps/api/src/modules/debit/debit.repository.ts, apps/api/src/modules/debit/debit.service.spec.ts, apps/api/src/modules/debit/debit.service.ts, apps/api/src/modules/job/application/application.repository.ts, apps/api/src/modules/refund/refund.controller.ts, apps/api/src/modules/refund/refund.module.ts, apps/api/src/modules/refund/refund.repository.ts, apps/api/src/modules/refund/refund.service.spec.ts, apps/api/src/modules/refund/refund.service.ts
- create refund module folder in backend
- move getRefundByApplicationId from debit to refund repository
- add ```PUT /refunds/jobs/:jobId/actors/:actorId/accept``` for admin to accept refund request
- send notification APPROVE_REFUND to actor and casting
- add ```PUT /refunds/jobs/:jobId/actors/:actorId/reject``` for admin to reject refund request
- send notification REJECT_REFUND to casting
- since not have view pending refund, need to inspect database of dev
- login as any admin
- https://api-dev.modela.miello.dev/swagger#/refunds/RefundController_acceptRefund
- accept some refund, view in db status is change from PENDING to ACCEPT and should send noti to actor and casting
- …
=> [171][174] Implement accept-reject refund request API @PUT

apps/api/src/modules/user/user.controller.ts, apps/api/src/modules/user/user.repository.ts, apps/api/src/modules/user/user.service.spec.ts, apps/api/src/modules/user/user.service.ts, pnpm-lock.yaml
- add ```GET /users/:userId/history``` for casting to view actor's work history or for users to view their own's work history
- login as any casting
- https://api-dev.modela.miello.dev/swagger#/users/UserController_getUsersWorkHistory
- get any actor's work history (userId from 11 to 20)
- should see all actor's work history that not refunded
- login as any actor or casting
- https://api-dev.modela.miello.dev/swagger#/users/UserController_getUsersWorkHistory
- get their own's work history (actor 11 to 20, casting 21 to 30)
- work history is only JobStatus FINISHED and ApplicationStatus OFFER_ACCEPTED
- the job available might few, try inspect …
=> [189] [192] Implement actor work history in actor and casting view API @GET

apps/api/src/modules/job/application/application.repository.ts
- Bring back missing `status` field
- https://api-dev.modela.miello.dev/swagger#/application/ApplicationController_findByJobId
=> [EX] Fix missing status field in get application by job id
